# Linear Regression (Single and Multiple)

## Formula

$$
\theta = (X^T \times X)^{-1} \times X^T \times y 
$$

Here  
X is the feature matrix, where each column is a feature, starting from $X_1, X_2, ... , X_n$  
y is the variable to be predicted  
$\theta$ is the coefficients of each feature starting from $b_0, b_1, b_2,..., b_n$

And the regression model is  
$$
\hat{y} = b_0 + b_1X_1 + b_2X_2 + ... + b_nX_n 
$$

In [23]:
import numpy as np

In [35]:
X = np.matrix([[1,1],
               [1,2],
               [1,3]])
        # each child array is matrix row

y = [1,2,3]

In [25]:
X.shape

(3, 2)

In [26]:
X.T

matrix([[0, 1, 2],
        [1, 2, 3]])

In [27]:
xt_x_mul = np.matmul(X.T,X)
xt_x_mul

matrix([[ 5,  8],
        [ 8, 14]])

In [28]:
xt_x_inv = np.linalg.inv(xt_x_mul)
xt_x_inv

matrix([[ 2.33333333, -1.33333333],
        [-1.33333333,  0.83333333]])

In [29]:
inv_xt_mul = np.matmul(xt_x_inv, X.T)
inv_xt_mul

matrix([[-1.33333333, -0.33333333,  0.66666667],
        [ 0.83333333,  0.33333333, -0.16666667]])

In [30]:
theta = np.matmul(inv_xt_mul, y)
np.round(theta, 0)

matrix([[-0.,  1.]])

## Final Code

In [31]:
def linear_regression_normal_equation(X: list[list[float]], y: list[float]) -> list[float]:
    # Your code here, make sure to round
    X = np.array(X)
    y = np.array(y)

    # Process
    xt_x_mul = np.matmul(X.T,X)
    xt_x_inv = np.linalg.inv(xt_x_mul)
    inv_xt_mul = np.matmul(xt_x_inv, X.T)
    theta = np.matmul(inv_xt_mul, y)
    
    return np.round(theta, 2)

In [37]:
print(linear_regression_normal_equation(X,y))

[-0.  1.]


In [38]:
print(linear_regression_normal_equation([[1, 3, 4], [1, 2, 5], [1, 3, 2]], [1, 2, 1]))

[ 4. -1. -0.]
